### ISSUE TITLE
URLDownloader failure in Airtame.download.recipe recipe

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/Tecnico1931-recipes#7]
`Error in local.munki.Airtame-dataJAR: Processor: URLDownloader: Error: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://downloads-cdn.airtame.com/get.php?platform=osx_x64&_ga', '--fail', '--output', '/Users/sadmin/Library/AutoPkg/Cache/local.munki.Airtame-dataJAR/downloads/tmpbk1c58cm']' returned non-zero exit status 22.`

Looking to build out a PR now

**Comment by Daz-wallace** [comment]
Looks like a minor URL change to https://downloads-website.airtame.com/get.php?platform=mac&amp;_ga
 PR incoming 😊

**Comment by neilmartin83** [comment]
Bump :)

**Comment by Daz-wallace** [comment]
Bump 😊

**Comment by neilmartin83** [comment]
![image](https://user-images.githubusercontent.com/10920581/98375966-c3cb3a80-203a-11eb-93a8-35b5fb0ee9f6.png)

**Comment by neilmartin83** [comment]
Bump. :)

**Comment by neilmartin83** [comment]
Bump.
